# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  
  config.vm.define :u2 do |config|
    config.vm.box = "ubuntu64"
    config.vm.network :hostonly, "10.33.33.33"
  end

  config.vm.define :u1 do |config|
    config.vm.box = "ubuntu64"
    config.vm.network :hostonly, "10.33.33.34"
    config.vm.forward_port 80, 8888
  end
end
